location="eastus"
rg-name="rg-staticweb-demo"
storage-account-name="staticwebsitedemo999"
index_document="index.html"
source_content="<h1>This is static content coming from the Terraform</h1>"
cdnprofile-name="static-web-demo-cdnprofile"
cdnprofile-sku="Standard_Microsoft"
cdn-endpoint-name="static-web-demo-cdn-endpoint"